### ISSUE TITLE
Model configuration file missing

### ISSUE THREAD

**Issue by takov751** [dnhkng/GlaDOS#1]
Greetings i have tried to run models with piper tts, but it was looking for the json file which is usually with the oxnn files

**Comment by takov751** [comment]
Renamed one of the official voice model config and now it's working. Chef kiss

**Comment by jonny190** [comment]
@takov751 What file did you use ?

**Comment by dnhkng** [comment]
OK, I have uploaded a JSON file to the model's directory. It's not needed for my project, but seems requested.

**Comment by takov751** [comment]
> OK, I have uploaded a JSON file to the model's directory. It's not needed for my project, but seems requested.

Thanks. Indeed for the project you don't need it, however piper requires it when you load the model
