### ISSUE TITLE
Limitation of scope?

### ISSUE THREAD

**Issue by phhusson** [dnhkng/GlaDOS#10]
Hi,

Thanks for this awesome project, it's really great. From the espeak-ng phonemizer rewrite (and non-GPLv3), to the low-requirement/onnx, glados voice itself (I just think it needs to learn how to pronounce "Ugh"), and the vad interruption is beautiful.

I'm not a full-blown LocalLLaMA: I want opensource models, and I prefer running them locally, but when I want to run Llama-3-70b, I compromise and use hosting services.

So, I made local modifications to use groq (currently free API but unlikely to last) or together.xyz (25$ free credit when logging in with a github account. llama3-70b requests are under 1c). asr/vad/tts still run locally, though asr might be interesting to offload as well.
It's currently nowhere near clean, hence not pushed anywhere.

But my question is whether you would merge such change in your repo, or you want to keep it tidy?
Another question wrt scope is about language: I'm a french native, and ggml-medium-32-2.en.bin simply don't understand me (I'm not blaming it). Ideally, I'd speak to it in french, and it would answer to me back in english. But I'm guessing some people would want a full french experience. Same question: Are those things you'd consider merging?

And my last question about scope is for function calling. It is very easy to just want to plug the whole world (I want to plug woob, selenium, Android's accessibility API with virtual displays, mpv, homeassistant, ...) but not very realistic especially if scaled to every user. So I wonder if you had a scope for function calling in mind?

Thanks again for your project!

**Comment by dnhkng** [comment]
I think its reasonable to offer multiple back ends in a config file.

I would suggest that the config file is where the selection of the whisper model lives; then the user can just download and choose a multilingual model.The same can go for the prompt; its probably better to have examples French questions there.  Just to note though: The minimal eSpeak code is focused on English, as is the voice model for GLaDOS. I expect the LLM will occasionally use French words, and it will be terrible.

I still need to look into the function call capabilities. I have reviewed a lot of options, but I really want to develop a clean and minimal code base, and not just import a big library that handles prompt processing in an opaque way.  I'm very open for suggestions on good libraries. I would aim at extracting the key ideas into a single module, as with TTS and ASR etc.

**Comment by phhusson** [comment]
Ok thanks. I'll start looking at it.

With regards to inputting french, I think it should be possible to force the LLM enough into english, I'll look at it, though so far I failed to have whisper output french -_-'

For function calling, I've personally done it completely manually from just the prompt, see https://github.com/phhusson/NOVA-AI/blob/master/llama-cpp.py#L18 for instance.
That's not a recommendation, it might be better to have a framework with already a set of functions plugged in, but I'm not aware of one.

**Comment by fonix232** [comment]
@dnhkng I think the best approach here would be to create "interfaces" (I know Python does not have them, I am using the word for lack of a better expression) for the three major components: STT, LLM and TTS. 

Then the implementations can be easily swapped even at runtime, while keeping your project clean - as long as any alternative STT/LLM/TTS project can adhere to the contract defined, they can be implemented with a simple wrapper.

As for multi-language support, maybe a Python-specific i18n approach could be used to retrieve the right strings, including, but not limited to:

- query prompt to use
- language models to use for STT/LLM/TTS
- default responses that are hardcoded, e.g. startup audio

That way all of these strings can be shuffled out to separate files, and further language support can be easily added, without messing up the codebase.

**Comment by dnhkng** [comment]
I think this is mostly done actually.

There are two methods that run in threads, one for the LLM, and one for TTS.

The 'interface' to each is a single python queue and flag.

The ASR portion of the code sends puts detected speech onto the queue, where it's processed by the LLM (could be hot swapped). The output generated text goes I to a queue for the TTS. This is consumed, and the output is audio. This could also be hot swapped.

There is also a flag to stop processing, when new user speech is detected. This could be made a python threading event.

So, yes, we could decouple the modules.

**Comment by dnhkng** [comment]
Actually, this should be moved to the Discord, as its more of a conversation than a concrete issue:
https://discord.com/invite/UaEjDZgT
