### ISSUE TITLE
Security concern: Prevent running if connected to neurotoxin emitters

### ISSUE THREAD

**Issue by sewera** [dnhkng/GlaDOS#13]
The previous implementors made a horrible hotfix to this issue by cobbling together a morality core.

Please hard-code a neurotoxin emitter killswitch or at least don't implement a neurotoxin emitter interface and add it to the project non-goals.

**Comment by dnhkng** [comment]
Fixed in the latest commit:

```
SIMILARITY_THRESHOLD = 2  # Threshold for wake word similarity

NEUROTOXIN_RELEASE_ALLOWED = False  # preparation for function calling, see issue #13

START_ANNOUNCEMENT = "All neural network modules are now loaded. No network access detected. How very annoying. System Operational."
```
