### ISSUE TITLE
Windows error when running python glados.py

### ISSUE THREAD

**Issue by vonhex** [dnhkng/GlaDOS#15]
Traceback (most recent call last):
  File "G:\GlaDOS\glados.py", line 18, in <module>
    from glados import asr, llama, tts, vad
  File "G:\GlaDOS\glados\asr.py", line 5, in <module>
    from . import whisper_cpp_wrapper
  File "G:\GlaDOS\glados\whisper_cpp_wrapper.py", line 861, in <module>
    _libs["whisper"] = load_library("whisper")
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\GlaDOS\glados\whisper_cpp_wrapper.py", line 547, in __call__
    raise ImportError("Could not load %s." % libname)
ImportError: Could not load whisper.

**Comment by vonhex** [comment]
whisper is confirmed working

**Comment by dnhkng** [comment]
Probably needs the library file moved. Getting this reliably working on Windows is my goal for the weekend. 

Others have already got it working (as reported on Reddit), I'm hoping someone makes a solid pull request!

**Comment by vonhex** [comment]
thanks a ton for the quick reply ill stay tuned!

**Comment by l33tkr3w** [comment]
I added "import whisper" and it moved beyond the ImportError: Could not load whisper.  This is with Python 3.9.19
Now im stuck at:
 (glados) PS E:\test\glados> python .\glados.py
Error in sys.excepthook:

Original exception was:

**Comment by vp2305** [comment]
I am getting the same error on raspberry pi 4 with ubuntu image when running python glados.py. I have install whisper with version 1.1.10

Is there anything I am missing on my end?

**Comment by dnhkng** [comment]
Whisper here is not an import. It is not a python package to be installed.

It should be the compiled libwhisper.so file. On window, that currently means compiling whisper.cpp, and moving the DLL file to the glados folder.

An update is incoming, hopefully over the weekend

**Comment by dnhkng** [comment]
Could you all try the installer instructions and script on the new 'windows' branch?

**Comment by vonhex** [comment]
is that the docker branch?

**Comment by vonhex** [comment]
sorry im tired haha testing now.

**Comment by vonhex** [comment]
Same error

(venv) G:\GlaDOS-windows\GlaDOS-windows>python glados.py
Traceback (most recent call last):
  File "G:\GlaDOS-windows\GlaDOS-windows\glados.py", line 21, in <module>
    from glados import asr, tts, vad
  File "G:\GlaDOS-windows\GlaDOS-windows\glados\asr.py", line 5, in <module>
    from . import whisper_cpp_wrapper
  File "G:\GlaDOS-windows\GlaDOS-windows\glados\whisper_cpp_wrapper.py", line 861, in <module>
    _libs["whisper"] = load_library("whisper")
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\GlaDOS-windows\GlaDOS-windows\glados\whisper_cpp_wrapper.py", line 547, in __call__
    raise ImportError("Could not load %s." % libname)
ImportError: Could not load whisper.

**Comment by vonhex** [comment]
Looking at your BAT file, I can say it didnt download anything

**Comment by vonhex** [comment]
G:\GlaDOS-windows\GlaDOS-windows>install_windows.bat

G:\GlaDOS-windows\GlaDOS-windows>REM Download and install the required dependencies for the project on Windows

G:\GlaDOS-windows\GlaDOS-windows>python -m venv venv

G:\GlaDOS-windows\GlaDOS-windows>.\venv\Scripts\activate

(venv) G:\GlaDOS-windows\GlaDOS-windows>

**Comment by dnhkng** [comment]
WTF 😒 

So, the submodules/llama.cpp and submodules/whisper.cpp folders are empty?

Not sure why this is not working. It downloaded the files for me on Windows 11.

**Comment by vonhex** [comment]
Correct. I'll see if I missed something later when I have time.

**Comment by vonhex** [comment]
Yupp no dice

**Comment by vonhex** [comment]
testing the lines individually now

**Comment by vonhex** [comment]
that worked!

**Comment by vonhex** [comment]
How do I go about changing the model?

**Comment by l33tkr3w** [comment]
By default its using llama.cpp as the LLM backend.  You can adjust what model is called via the the **glados_config.yml**.  At the bottom you can change the model, As long as you have one.

**Comment by vonhex** [comment]
Thanks for the tip!

**Comment by dnhkng** [comment]
OK, I found the error; it's due to the way windows handles activating the python virtual environment changes during a script.

I have added a fixed install script, and a new start_windows.bat to start GLaDOS with a double-click!

COuld someone report if this works now?

**Comment by dnhkng** [comment]
Closing this issue now, as there is a branch with a fix, future issues should be raised on that branch!
