### ISSUE TITLE
Windows library issues

### ISSUE THREAD

**Issue by IngilizAdam** [dnhkng/GlaDOS#18]
```Phonemizer``` class is crashing in ```__init__``` due to loading ```libc.so.6```. Since Windows doesn't have that shared object, this is expected.

Simple solution would be to use ```msvcrt``` instead of ```libc.so.6``` in Windows but this class doesn't include some of the method definitions such as ```open_memstream```. So we also need to check OS each time we access this object and select the accurate method definition.

Or we can create a C program to provide access to the necessary methods and compile it into a shared object or DLL. And then load that library instead of ```msvcrt``` and ```libc```.  This way code would be much cleaner imho.

I can work on the desired solution.

**Comment by Feror-BotMaker** [comment]
Same issue on MacOS and my instance of Ubuntu

**Comment by IngilizAdam** [comment]
> Same issue on MacOS and my instance of Ubuntu

Check the link below to fix it in Ubuntu

https://askubuntu.com/questions/189318/missing-lib-libc-so-6

**Comment by Traxmaxx** [comment]
> Same issue on MacOS and my instance of Ubuntu

Check my comments on this PR for a MacOS fix: https://github.com/dnhkng/GlaDOS/pull/9

**Comment by dnhkng** [comment]
This was fixed in #33
