### ISSUE TITLE
Proper discussion channel(s)?

### ISSUE THREAD

**Issue by fonix232** [dnhkng/GlaDOS#19]
Given the traction of this project, I think it would be worthwhile to "invest" into some form of communication that allows a bit quicker interaction than GitHub comments. Possibly a Telegram channel or Discord server, or maybe even a Matrix room?

**Comment by dnhkng** [comment]
![star-history-202453](https://github.com/dnhkng/GlaDOS/assets/2691732/ef872568-61bd-4956-b6f5-c90c0f666ace)


Yes... There has been 'traction' 😮


This was a little hobby project. I was not expecting this level of excitement...


I will set up a discord for discussing the current state of the code base, a d collect ideas for next steps and future directions.

**Comment by fonix232** [comment]
That Reddit post certainly helped 😉

**Comment by dnhkng** [comment]
https://discord.com/invite/EAVfFZjG

Please join, and let's build a community!
