### ISSUE TITLE
Logo needed

### ISSUE THREAD

**Issue by dnhkng** [dnhkng/GlaDOS#20]
As we seems to have a community around this project, I think we need a logo!

Please post your ideas (they of course are allowed to be AI Generated 👍) in the discord General channel.

https://discord.com/invite/EAVfFZjG

**Comment by im-ukr** [comment]
having a logo would be cool

**Comment by dnhkng** [comment]
Yeah, they expire. Here's a new link:
https://discord.com/invite/ThgtEwnY

**Comment by DrCheeseFace** [comment]
wheatley would be fun

**Comment by Ghostboo-124** [comment]
A logo has been created

**Comment by dnhkng** [comment]
Thanks!
