### ISSUE TITLE
ASR Emitting Exclamation Points Standalone Tests

### ISSUE THREAD

**Issue by LegendBegins** [dnhkng/GlaDOS#27]
Hi,

I'm trying to test the ASR functionality with WAV files using the included code, but it's returning a long string of `!!!!!`, no matter what .wav file I use. They've been encoded to 16k pcm_s16le. Any chance we could get a "known good" sample wav file or some clarity on using `transcribe` independently?

My overarching use case is to transcribe streamed audio from a non-mic source, so I'm trying to decouple glados from sounddevice and running into this issue.

**Comment by dnhkng** [comment]
In that case you should use [whisper.cpp](https://github.com/ggerganov/whisper.cpp) directly.

My implementation is designed to fit the 30-second long samples Whisper uses for inference. The main whisper.cpp project is much more advanced, and can handle wav files that are hours long, and has a simple to use command line interface.

**Comment by LegendBegins** [comment]
Maybe I should clarify. I have a device streaming raw audio samples over a network connection and I'm convert it into the same np byte arrays produced by `sounddevice.InputStream` so I can implement glados on a device without a local microphone—right now, I'm just trying to sanity-check ASR, which is failing to transcribe short samples (<30 seconds) on my end.

**Comment by dnhkng** [comment]
When you play the audio back, can you hear anything? 

TBH, I forget the range of the audio now. When I first started playing with this system, I was checking things like the dtype, range within the dtype (eg sometimes I saw that the range was -0.1 to 0.1 on a float!), and tried fixing the dynamic range. But that was a year ago, and recording with sounddevice just worked, so I stopped those investigations.

**Comment by LegendBegins** [comment]
Yep, the audio works fine on normal playback, but no matter what I set the dynamic range to, ASR always returns `!!!!!!!!!!...`. I've read that might be Whisper outputting all zeroes, but I haven't explored that in depth yet. Interestingly, the byte string it returns is always the same length, irrespective of the audio length.

My options here may be to
A) Reverse Engineer how `sounddevice` builds its arrays and reimplement it with raw samples.
B) Configure some kind of virtual microphone to stream samples into and pick that up as a sound device.
C) Reimplement the core transcription functionality with different ASR and VAD libraries. But I'm not confident I'll be able to optimize it down to your demo's seamless interruption/pause detection.

**Comment by LegendBegins** [comment]
That was it. Thank you so much!!

I'm really excited to integrate this project for my use case. Appreciate you taking the time to put it together.
