### ISSUE TITLE
Robotic Hardware

### ISSUE THREAD

**Issue by mawildoer** [dnhkng/GlaDOS#28]
Hi @dnhkng , what do you have in mind for the hardware for GlaDOS?
I could potentially lend a hand with the electronics.

**Comment by dnhkng** [comment]
I was thinking Odrive motor controller, for nice fast animatronics.

To start with, matching the in-game movements of GLaDOS, and similar speed. We'll also inverse kinematics, for thing like tracking the user with a webcam.

Interesting for you?

**Comment by mawildoer** [comment]
I'm personally keen on electronics design, and would probably leave the kinematics and mechanical work for others if that's alright.

I recently helped put together this motor controller: https://github.com/atopile/spin-servo-drive
The design is portable, so it'd be easy enough enough put a few of these together on a board for however many axes we need.

I'm imagining something along the lines of:
- Some servo axes for fast/high power axes
- Some stepper axes for the slower/stiffer joints
- An RP2040 or ESP32 as a main micro to coordinate things and do comms to the computer

Maybe a handful or sensors back to do things like endstops?

**Comment by dnhkng** [comment]
Those servos look great!

The price is also great. Could you have a look at GLaDOS' movements, and get a BOM on the components?

**Comment by ben-gineering** [comment]
hey,
just throwing this dude's youtube channel in here:
https://www.youtube.com/@MrVolt/videos

he built a animatronic glados, wheatley and other stuff. i don't remember if he published the files, but at the very least its probably worth watching just to avoid the design mistakes he already made :)

**Comment by dnhkng** [comment]
Closing this, as the chat should move to Discord. 

https://discord.com/invite/UaEjDZgT
