### ISSUE TITLE
Raspberry pi 5 version: glados.llama.ServerStartupError: Failed to startup!

### ISSUE THREAD

**Issue by Kosubotto** [dnhkng/GLaDOS#35]
Looking to experiment with this repo on raspberry pi 5 with an LCD screen attached. individually the espeak, and sub directories whisper and llama work great. 

when i execute python glados.py from working dir i get following error: 
ython glados.py
Couldn't establish connection after max_connection_attempts=10
Traceback (most recent call last):
  File "/home/admin/GlaDOS/glados.py", line 536, in <module>
    llama_server.start()
  File "/home/admin/GlaDOS/glados/llama.py", line 97, in start
    raise ServerStartupError("Failed to startup! Check the error log messages")
glados.llama.ServerStartupError: Failed to startup! Check the error log messages

i have downloaded vscode and explored the demo.ipynb  and i have an error on the TTS engine. 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], [line 2](vscode-notebook-cell:?execution_count=4&line=2)
      [1](vscode-notebook-cell:?execution_count=4&line=1) # Instantiate the TTS engine
----> [2](vscode-notebook-cell:?execution_count=4&line=2) glados_tts = tts.TTSEngine()

AttributeError: module 'glados.tts' has no attribute 'TTSEngine'

to clarify here, would these be related ?

note i used make for raspberry pi and did not use CUDA... not sure if that breaks the design?

**Comment by dnhkng** [comment]
Ok, there are two separate issues here. For the first one, the llama server is not working correctly.

Try to see if it works manually,.by staring the server you compiled in submodules/llama.cpp


The second issue is the TTS engine. That was just removed recently, and I forgot to remove the reference in the demo. I'll fix it soon, thanks for bringing this to my attention.
