### ISSUE TITLE
New windows install initialized with wrong model

### ISSUE THREAD

**Issue by Sgnarf** [dnhkng/GlaDOS#37]
Using the windows install and then running it, you get an error as the default model in the config file is different from the one downloaded by the installer (downloaded: Meta-Llama-3-8B-Instruct-IQ3_XS.gguf, config file: ./models/Meta-Llama-3-8B-Instruct-Q6_K.gguf)

It should be the same to avoid error.

**Comment by dnhkng** [comment]
Should be fixed now, thanks for the head's up!
