### ISSUE TITLE
GlaDOS gets interrupted by itself when on speaker

### ISSUE THREAD

**Issue by Sgnarf** [dnhkng/GlaDOS#38]
If I run GlaDOS with speaker and microphone, it hears itself speaking and assume that's the answer (e.g. the first few word of the response become the input) getting stuck in a forever loop.

The issue is not there if using headset+mic, where it can't hear its own answers. 

I don't know if it's a system issue (I'm currently on Windows) or if it can be managed within the GlaDOS libraries...

**Comment by dnhkng** [comment]
This needs a noise cancelling microphone. A room speaker system is needed.

**Comment by dnhkng** [comment]
I have created a new branch that makes interruption optional in #39. That should stop the loop problem, but prevents you from interrupting GLaDOS. 

Could you test it out, and see if if solves your issue?

**Comment by bitbyteboom** [comment]
Also, may be a good idea to note need for noise canceling setup or headphones / headset for interruption to work, in the README.

**Comment by dnhkng** [comment]
I added that to the 'Help Section' on the new branch.

**Comment by Sgnarf** [comment]
I've cheked the new version and with interruptible = false it does work. However the "user experience" is a bit different, as you can't interrupt the model if it starts rambling about stuffs :D

**Comment by dnhkng** [comment]
Yes, thats how is works. 

If you find the answers too long, go ahead and modify the system prompt and ask for shorter responses.
