### ISSUE TITLE
start_windows.bat fails to launch GlaDOS when python 3.9 is previously installed.

### ISSUE THREAD

**Issue by l33tkr3w** [dnhkng/GlaDOS#41]
Noticed that when glaDOS.py would attempt to launch I would just get a new line and no execution.  Checking python --verison I see that the automatically created venv was using python 3.9.  Switching to a venv of python 3.12.3 worked for me. 

Maybe it could be explicitly defined.  Good work

**Comment by dnhkng** [comment]
sure, will push a fix now!

**Comment by dnhkng** [comment]
Fixed in commit e0d9198
