### ISSUE TITLE
CPU usage during idle listening 50%

### ISSUE THREAD

**Issue by l33tkr3w** [dnhkng/GlaDOS#43]
I see that when GlaDOS is sitting idle and just "Listening..." my CPU usage is hovering at 50% usage on a 14900k.
Is this expected?  Im just tryiong to determine if this is expected or if im not using a Cuda library somewhere.
This is with the recent windows installer.

**Comment by dnhkng** [comment]
Seems like its inferencing on CPU.

**Comment by l33tkr3w** [comment]
Im still troubleshooting.  Seems like everything is running on cudda except for onnxruntime.  When I check my device info with ```
>> import onnxruntime as rt
>> rt.get_device()
'GPU'
```

**Comment by dnhkng** [comment]
Make sure you have uninstalled onnxruntime before installing onnxruntime-gpu.

**Comment by l33tkr3w** [comment]
> Make sure you have uninstalled onnxruntime before installing onnxruntime-gpu.

while in venv I did 
pip uninstall onnxruntime
pip uninstall onnxruntime-gpu
pip cache purge
pip install onnxruntime-gpu

Still sits at 45-50% usage.    It sees the device as GPU but somehow sets the provider to CPU.

**Comment by dnhkng** [comment]
Seems this is CPU only.

https://github.com/snakers4/silero-vad/discussions/388
