### ISSUE TITLE
Erorr when using with home assistant

### ISSUE THREAD

**Issue by fmaddict** [dnhkng/GlaDOS#5]
When using the GlaDOS model in Home Assitant it's unable to play any tts from the model, thinking for a while and then timing out.
When testing with a local windows copy of piper the model worked fine.

To Fix, change the dataset on line 2 in glados.onnx.json to match the file name, eg
`    "dataset": "glados",`

Unsure if you want to change the .json file here as I don't know if that will affect any other uses, but thought I'd document this here incase anyone else tries to put it into HA like I did.

**Comment by dnhkng** [comment]
Fixed!

I added the JSON as a request, and have never tested it. Thanks for doing so!
