### ISSUE TITLE
start_windows fails to launch

### ISSUE THREAD

**Issue by GameMelvin** [dnhkng/GlaDOS#84]
Hi, the install goes as it should but as soon as I use the start file it opens CMD for a second before closing again and not starting anything.

**Comment by thijsi123** [comment]
It's most likely this error:
```
2024-09-19 17:51:51.582 | ERROR    | glados.llama:is_running:173 - Couldn't establish connection after max_connection_attempts=10
Traceback (most recent call last):
  File "T:\AI\GlaDOS\glados.py", line 594, in <module>
    start()
  File "T:\AI\GlaDOS\glados.py", line 573, in start
    llama_server.start()
  File "T:\AI\GlaDOS\glados\llama.py", line 125, in start
    raise ServerStartupError("Failed to startup! Check the error log messages")
glados.llama.ServerStartupError: Failed to startup! Check the error log messages
```

**Comment by thijsi123** [comment]
Try adding PAUSE at the end of start_windows.bat and run again.

so like this:

@echo off
REM Start GLaDOS

call .\venv\Scripts\activate
python glados.py
PAUSE

**Comment by GameMelvin** [comment]
Traceback (most recent call last):
  File "C:\Users\gamem\Desktop\GlaDOS-main\glados.py", line 21, in <module>
    from glados import asr, tts, vad
  File "C:\Users\gamem\Desktop\GlaDOS-main\glados\asr.py", line 6, in <module>
    from . import whisper_cpp_wrapper
  File "C:\Users\gamem\Desktop\GlaDOS-main\glados\whisper_cpp_wrapper.py", line 861, in <module>
    _libs["whisper"] = load_library("whisper")
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gamem\Desktop\GlaDOS-main\glados\whisper_cpp_wrapper.py", line 547, in __call__
    raise ImportError("Could not load %s." % libname)
ImportError: Could not load whisper.

This is the error I get

**Comment by thijsi123** [comment]
Did you install using install_windows.bat? (I'm no expert in this, but I'll try to help.)

**Comment by GameMelvin** [comment]
Yes, I used the install_windows.bat.

**Comment by thijsi123** [comment]
Can you confirm that submodules\whisper.cpp folder exists? In glados folder?

**Comment by GameMelvin** [comment]
Yes. both exist in the folder
![Screenshot 2024-09-19 180352](https://github.com/user-attachments/assets/6cac5994-9998-4f31-8672-463c69ee61cf)

**Comment by thijsi123** [comment]
Could you remove them and rerun the installer?

**Comment by thijsi123** [comment]
I mean this:

```
echo Downloading Llama...
curl -L "https://github.com/ggerganov/llama.cpp/releases/download/b3266/cudart-llama-bin-win-cu12.2.0-x64.zip" --output "cudart-llama-bin-win-cu12.2.0-x64.zip"
curl -L "https://github.com/ggerganov/llama.cpp/releases/download/b3266/llama-b3266-bin-win-cuda-cu12.2.0-x64.zip" --output "llama-bin-win-cuda-cu12.2.0-x64.zip"
echo Unzipping Llama...
tar -xf cudart-llama-bin-win-cu12.2.0-x64.zip -C submodules\llama.cpp
tar -xf llama-bin-win-cuda-cu12.2.0-x64.zip -C submodules\llama.cpp

echo Downloading Whisper...
curl -L "https://github.com/ggerganov/whisper.cpp/releases/download/v1.6.0/whisper-cublas-12.2.0-bin-x64.zip" --output "whisper-cublas-12.2.0-bin-x64.zip"
echo Unzipping Whisper...
tar -xf whisper-cublas-12.2.0-bin-x64.zip -C submodules\whisper.cpp

```

**Comment by GameMelvin** [comment]
Still gives the same error.

**Comment by thijsi123** [comment]
IS python 3.12 installed and does it show up like this in cmd?
C:\Users\xxx>python -V
Python 3.12.6   (should be 3.12.x)
and if it doesn't show like this try this command:
C:\Users\xxx>python3.12
Python 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

if it works it should be alright. No need to worry about "C:\Users\xxx>python -V"

attempt 2:

run this as a bat file
```
@echo off

:: Downloading Whisper
echo Downloading Whisper...
curl -L "https://github.com/ggerganov/whisper.cpp/releases/download/v1.6.0/whisper-cublas-12.2.0-bin-x64.zip" --output "whisper-cublas-12.2.0-bin-x64.zip"

:: Creating submodules directory for Whisper
echo Creating submodules directory for Whisper...
mkdir submodules\whisper.cpp

:: Unzipping Whisper using PowerShell with overwrite
echo Unzipping Whisper using PowerShell...
powershell -Command "Expand-Archive -Path 'whisper-cublas-12.2.0-bin-x64.zip' -DestinationPath 'submodules\whisper.cpp' -Force"

:: Cleaning up Whisper zip file
echo Cleaning up...
del whisper-cublas-12.2.0-bin-x64.zip

:: Downloading Llama
echo Downloading Llama...
curl -L "https://github.com/ggerganov/llama.cpp/releases/download/b3266/cudart-llama-bin-win-cu12.2.0-x64.zip" --output "cudart-llama-bin-win-cu12.2.0-x64.zip"
curl -L "https://github.com/ggerganov/llama.cpp/releases/download/b3266/llama-b3266-bin-win-cuda-cu12.2.0-x64.zip" --output "llama-b3266-bin-win-cuda-cu12.2.0-x64.zip"

:: Creating submodules directory for Llama
echo Creating submodules directory for Llama...
mkdir submodules\llama.cpp

:: Unzipping Llama using PowerShell with overwrite
echo Unzipping Llama using PowerShell...
powershell -Command "Expand-Archive -Path 'cudart-llama-bin-win-cu12.2.0-x64.zip' -DestinationPath 'submodules\llama.cpp' -Force"
powershell -Command "Expand-Archive -Path 'llama-b3266-bin-win-cuda-cu12.2.0-x64.zip' -DestinationPath 'submodules\llama.cpp' -Force"

:: Cleaning up Llama zip files
echo Cleaning up...
del cudart-llama-bin-win-cu12.2.0-x64.zip
del llama-b3266-bin-win-cuda-cu12.2.0-x64.zip

echo Done!


```

if that doesn't work then... I don't know. Maybe the path in the following is wrong? 
GlaDOS\glados\whisper_cpp_wrapper.py on line 858


```
"add_library_search_dirs(['./submodules/whisper.cpp/'])  # add the path to the whisper.cpp submodule

# Begin libraries
_libs["whisper"] = load_library("whisper")"

```
You could change it to `r"C:/Users/gamem/Desktop/GlaDOS-main/submodules/whisper.cpp/"` like this.

**Comment by thijsi123** [comment]
That's all I can think of... Sorry if it doesn't help.

**Comment by GameMelvin** [comment]
Traceback (most recent call last):
  File "C:\Users\gamem\Desktop\GlaDOS-main\glados.py", line 21, in <module>
    from glados import asr, tts, vad
  File "C:\Users\gamem\Desktop\GlaDOS-main\glados\asr.py", line 6, in <module>
    from . import whisper_cpp_wrapper
  File "C:\Users\gamem\Desktop\GlaDOS-main\glados\whisper_cpp_wrapper.py", line 861, in <module>
    _libs["whisper"] = load_library("whisper")
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gamem\Desktop\GlaDOS-main\glados\whisper_cpp_wrapper.py", line 547, in __call__
    raise ImportError("Could not load %s." % libname)
ImportError: Could not load whisper.

I did the last thing by changing the code and this is the new error I get.

**Comment by thijsi123** [comment]
It's the same, no idea. Sorry.

**Comment by F4u5t** [comment]
same issue here in win10

**Comment by dnhkng** [comment]
This is a huge pain, due to using whisper DLLs and wrappers.

I'm currently refactoring GLaDOS to use Nemo Parakeet,.which has better performance, speed and runs on GPU with less pain.
