### ISSUE TITLE
Interupts Itself with It's Own Speaking

### ISSUE THREAD

**Issue by tommywright** [dnhkng/GlaDOS#86]
When I run GlaDOS on my system (external speakers), the microphone picks up her speaking so it interrupts her. She is constantly being interrupted by her own voice. What am I doing wrong?

**Comment by dnhkng** [comment]
Hi,

You can either turn off interruption mode in the configuration file, of get a room-style microphone/speaker device, like a Jabra. These have built in echo cancellation, so GLaDOS can't hear herself.
